/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAPIConsumer, IAPIConsumerInterface } from "../IAPIConsumer";

const _abi = [
  {
    inputs: [],
    name: "requestVolumeData",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "volume",
    outputs: [
      {
        internalType: "uint152",
        name: "",
        type: "uint152",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAPIConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IAPIConsumerInterface {
    return new utils.Interface(_abi) as IAPIConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAPIConsumer {
    return new Contract(address, _abi, signerOrProvider) as IAPIConsumer;
  }
}
