/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReputationAccessor,
  ReputationAccessorInterface,
} from "../ReputationAccessor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_api_consumer",
        type: "address",
      },
    ],
    name: "getReputationScore",
    outputs: [
      {
        internalType: "uint152",
        name: "",
        type: "uint152",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_api_consumer",
        type: "address",
      },
    ],
    name: "requestReputationScore",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103a0806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806375a67d5c1461003b578063dede852f1461006b575b600080fd5b610055600480360381019061005091906101ea565b61009b565b60405161006291906102aa565b60405180910390f35b610085600480360381019061008091906101ea565b610122565b604051610092919061028f565b60405180910390f35b60008173ffffffffffffffffffffffffffffffffffffffff1663c618a1e46040518163ffffffff1660e01b815260040160206040518083038186803b1580156100e357600080fd5b505afa1580156100f7573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061011b9190610244565b9050919050565b60008173ffffffffffffffffffffffffffffffffffffffff16636021abac6040518163ffffffff1660e01b8152600401602060405180830381600087803b15801561016c57600080fd5b505af1158015610180573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101a49190610217565b9050919050565b6000813590506101ba81610325565b92915050565b6000815190506101cf8161033c565b92915050565b6000815190506101e481610353565b92915050565b600060208284031215610200576101ff610320565b5b600061020e848285016101ab565b91505092915050565b60006020828403121561022d5761022c610320565b5b600061023b848285016101c0565b91505092915050565b60006020828403121561025a57610259610320565b5b6000610268848285016101d5565b91505092915050565b61027a816102d7565b82525050565b610289816102e1565b82525050565b60006020820190506102a46000830184610271565b92915050565b60006020820190506102bf6000830184610280565b92915050565b60006102d082610300565b9050919050565b6000819050919050565b600072ffffffffffffffffffffffffffffffffffffff82169050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600080fd5b61032e816102c5565b811461033957600080fd5b50565b610345816102d7565b811461035057600080fd5b50565b61035c816102e1565b811461036757600080fd5b5056fea2646970667358221220c8678d8a663129670081b805ed568139bba2fc473f11ea7e4232a4f53b34d60664736f6c63430008070033";

type ReputationAccessorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReputationAccessorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReputationAccessor__factory extends ContractFactory {
  constructor(...args: ReputationAccessorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ReputationAccessor";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReputationAccessor> {
    return super.deploy(overrides || {}) as Promise<ReputationAccessor>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ReputationAccessor {
    return super.attach(address) as ReputationAccessor;
  }
  connect(signer: Signer): ReputationAccessor__factory {
    return super.connect(signer) as ReputationAccessor__factory;
  }
  static readonly contractName: "ReputationAccessor";
  public readonly contractName: "ReputationAccessor";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReputationAccessorInterface {
    return new utils.Interface(_abi) as ReputationAccessorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReputationAccessor {
    return new Contract(address, _abi, signerOrProvider) as ReputationAccessor;
  }
}
