/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ReputationAccessorInterface extends utils.Interface {
  contractName: "ReputationAccessor";
  functions: {
    "getReputationScore(address)": FunctionFragment;
    "requestReputationScore(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getReputationScore",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReputationScore",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReputationScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReputationScore",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ReputationAccessor extends BaseContract {
  contractName: "ReputationAccessor";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReputationAccessorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReputationScore(
      _api_consumer: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    requestReputationScore(
      _api_consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getReputationScore(
    _api_consumer: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  requestReputationScore(
    _api_consumer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getReputationScore(
      _api_consumer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestReputationScore(
      _api_consumer: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getReputationScore(
      _api_consumer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestReputationScore(
      _api_consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReputationScore(
      _api_consumer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestReputationScore(
      _api_consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
